version: '2'

services:
  nginx:
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "80"
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    restart: always

  mariadb:
    restart: always
    ports:
      - ${MYSQL_BIND_PORT}:3306

networks:
  default:
    external:
      name: ${PROXY_NETWORK}



